'use strict';
(() => {
const $=id=>document.getElementById(id), viewport=$('viewport'),scene=$('scene'),player=$('player'),journal=$('journal');
const locations=window.villageLocations;
const WORLD_WIDTH=3000,WORLD_HEIGHT=2000;
const state={x:1500,y:720,path:[],pending:null,near:null,visited:new Set(),keys:new Set(),last:0,scale:1,ox:0,oy:0,zoom:.7,overview:false,motion:!matchMedia('(prefers-reduced-motion: reduce)').matches,sound:false,soundWanted:false,welcomed:false};
const STORAGE_KEY='neo-village-preferences-v1';
function savePreferences(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({visited:[...state.visited],motion:state.motion,sound:state.soundWanted,zoom:state.zoom}));}catch{}}
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved&&typeof saved==='object'){if(Array.isArray(saved.visited))state.visited=new Set(saved.visited.filter(id=>Object.hasOwn(locations,id)));if(typeof saved.motion==='boolean'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)state.motion=saved.motion;if(Number.isFinite(saved.zoom))state.zoom=Math.max(.45,Math.min(1.1,saved.zoom));state.soundWanted=saved.sound===true;$('saved-sound').hidden=!state.soundWanted;}}catch{}
function progress(){const count=state.visited.size;$('quest-progress').textContent=count===8?'All corners discovered. You lovely completionist.':`Discover 8 neighborhoods · ${count} / 8`;$('found').textContent=count+' / 8';document.querySelectorAll('.dock [data-open]').forEach(b=>b.classList.toggle('visited',state.visited.has(b.dataset.open)));}
progress();
$('reset-preferences').addEventListener('click',()=>{try{localStorage.removeItem(STORAGE_KEY);}catch{}state.visited.clear();state.motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;state.zoom=.7;state.sound=false;state.soundWanted=false;clearInterval(audioTimer);audioContext?.suspend();$('sound').textContent='Sound: off';$('sound').setAttribute('aria-pressed','false');$('saved-sound').hidden=true;motionUI();progress();savePreferences();say('A fresh page in the storybook.');});
let speechTimer,returnFocus=null,audioContext=null,audioTimer=null,melodyIndex=0;
const blocks=[{l:1095,r:1145,t:840,b:880},{l:1885,r:1935,t:1170,b:1210},{l:405,r:795,t:235,b:510},{l:1305,r:1695,t:125,b:400},{l:2140,r:2690,t:225,b:510},{l:2310,r:2720,t:785,b:1050},{l:2140,r:2595,t:1230,b:1600},{l:1305,r:1695,t:1360,b:1680},{l:305,r:795,t:1240,b:1570},{l:315,r:705,t:785,b:1050}];
const walkable=(x,y)=>x>=80&&x<=2820&&y>=80&&y<=1920&&!blocks.some(b=>x>b.l&&x<b.r&&y>b.t&&y<b.b);
const clamp=(v,lo,hi)=>Math.min(hi,Math.max(lo,v));
function announce(text){$('announcement').textContent=text;}
function say(text,duration=5000){clearTimeout(speechTimer);$('speech').textContent=text;$('speech').hidden=false;announce(text);speechTimer=setTimeout(()=>$('speech').hidden=true,duration);}
function welcomeOff(){state.welcomed=true;$('welcome').classList.add('hidden');}
function lineClear(a,b){const count=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/10);for(let i=0;i<=count;i++){const t=count?i/count:0;if(!walkable(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t))return false;}return true;}
function route(tx,ty){
 if(!walkable(tx,ty))return [];
 const start={x:state.x,y:state.y},goal={x:tx,y:ty};if(lineClear(start,goal))return [goal];
 const size=25,cols=121,rows=81,key=(x,y)=>y*cols+x;const sx=Math.round(start.x/size),sy=Math.round(start.y/size),gx=Math.round(tx/size),gy=Math.round(ty/size);
 const queue=[[sx,sy]],seen=new Set([key(sx,sy)]),parent=new Map();let end=null;
 for(let head=0;head<queue.length;head++){const [x,y]=queue[head];if(x===gx&&y===gy){end=[x,y];break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=key(nx,ny);if(nx<0||ny<0||nx>=cols||ny>=rows||seen.has(k)||!walkable(nx*size,ny*size))continue;seen.add(k);parent.set(k,[x,y]);queue.push([nx,ny]);}}
 if(!end)return [];
 let points=[goal];for(let p=end;p&&(p[0]!==sx||p[1]!==sy);p=parent.get(key(...p)))points.push({x:p[0]*size,y:p[1]*size});points.reverse();
 const smooth=[];let from=start,index=0;while(index<points.length){let last=index;for(let j=index;j<points.length;j++){if(lineClear(from,points[j]))last=j;else break;}smooth.push(points[last]);from=points[last];index=last+1;}return smooth;
}
function travel(id){welcomeOff();state.overview=false;state.keys.clear();const p=locations[id];state.path=route(p.x,p.y);state.pending=id;if(!state.path.length){state.pending=null;openJournal(id);return;}showTarget(p.x,p.y);say('Off to '+p.title.toLowerCase()+'.',3000);viewport.focus({preventScroll:true});}
function showTarget(x,y){$('destination').style.left=x+'px';$('destination').style.top=y+'px';$('destination').style.display='block';}
function camera(){const w=viewport.clientWidth,h=viewport.clientHeight;state.scale=state.overview?Math.min(w/WORLD_WIDTH,h/WORLD_HEIGHT):state.zoom;const sw=WORLD_WIDTH*state.scale,sh=WORLD_HEIGHT*state.scale;const tx=sw<w?(w-sw)/2:clamp(w/2-state.x*state.scale,w-sw,0),ty=sh<h?(h-sh)/2:clamp(h*.53-state.y*state.scale,h-sh,0);const ease=state.motion&&state.lastScale===state.scale?.2:1;state.ox+=(tx-state.ox)*ease;state.oy+=(ty-state.oy)*ease;state.lastScale=state.scale;scene.style.transform=`translate(${state.ox}px,${state.oy}px) scale(${state.scale})`;$('zoom-level').textContent=Math.round(state.scale*100)+'%';$('overview').setAttribute('aria-pressed',String(state.overview));$('zoom-out').disabled=!state.overview&&state.zoom<=.45;$('zoom-in').disabled=!state.overview&&state.zoom>=1.1;$('map-player').style.left=state.x/WORLD_WIDTH*100+'%';$('map-player').style.top=state.y/WORLD_HEIGHT*100+'%';}
function showMap(open){$('village-map').hidden=!open;$('toggle-map').setAttribute('aria-expanded',String(open));if(open){welcomeOff();state.keys.clear();$('close-map').focus();}else $('toggle-map').focus();}
$('toggle-map').addEventListener('click',()=>showMap($('village-map').hidden));$('close-map').addEventListener('click',()=>showMap(false));
$('zoom-in').addEventListener('click',()=>{state.overview=false;state.zoom=clamp(state.zoom+.1,.45,1.1);savePreferences();camera();});$('zoom-out').addEventListener('click',()=>{state.overview=false;state.zoom=clamp(state.zoom-.1,.45,1.1);savePreferences();camera();});$('overview').addEventListener('click',()=>{welcomeOff();state.overview=!state.overview;camera();});
document.querySelectorAll('[data-fast]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.fast,p=locations[id];state.x=p.x;state.y=p.y;state.overview=false;showMap(false);draw();openJournal(id);}));

function draw(){player.style.zIndex=String(100+Math.floor(state.y));player.style.left=state.x+'px';player.style.top=state.y+'px';camera();let nearest=null,distance=145;for(const [id,p]of Object.entries(locations)){const d=Math.hypot(state.x-p.x,state.y-p.y);if(d<distance){nearest=id;distance=d;}}if(nearest!==state.near){state.near=nearest;document.querySelectorAll('[data-travel]').forEach(b=>b.classList.toggle('near',b.dataset.travel===nearest));$('interact').hidden=!nearest;if(nearest)$('interact').innerHTML='Enter '+locations[nearest].title.toLowerCase()+' <kbd>E</kbd>';}}
function openJournal(id){if(!locations[id]&&id!=='resume')return;const meta=locations[id]||{title:"The recruiter shortcut",note:"All the chapters. None of the commute."};welcomeOff();state.keys.clear();state.path=[];state.pending=null;$('destination').style.display='none';if(!journal.open)returnFocus=document.activeElement;if(locations[id])state.visited.add(id);$('journal-title').textContent=meta.title;$('journal-footer').textContent=meta.note;$('journal-eyebrow').textContent='NEO’S FIELD NOTES / '+(locations[id]?.icon||'01');$('journal-content').innerHTML=window.portfolioSections[id];if(id==='work')window.mountBackendLab($('journal-content'));$('journal-content').querySelectorAll('a[href="#work"]').forEach(a=>a.addEventListener('click',event=>{event.preventDefault();openJournal('work');}));$('journal-content').querySelectorAll('[data-section-open]').forEach(b=>b.addEventListener('click',()=>openJournal(b.dataset.sectionOpen)));const count=state.visited.size;$('quest-progress').textContent=count===8?'All corners discovered. You lovely completionist.':`Discover 8 neighborhoods · ${count} / 8`;$('found').textContent=count+' / 8';document.querySelectorAll('.dock [data-open]').forEach(b=>b.classList.toggle('visited',state.visited.has(b.dataset.open)));savePreferences();if(!journal.open)journal.showModal();journal.scrollTop=0;$('close-journal').focus();tone(523,.12);announce(meta.title+' opened.');}
function closeJournal(){journal.close();if(state.visited.size===8)say('100% explored. 0% meetings required.',7000);if(returnFocus?.isConnected)returnFocus.focus({preventScroll:true});else viewport.focus({preventScroll:true});}
function tone(frequency,duration=.8){if(!state.sound||!audioContext||document.hidden)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type='sine';oscillator.frequency.value=frequency;const now=audioContext.currentTime;gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.028,now+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);oscillator.connect(gain);gain.connect(audioContext.destination);oscillator.start();oscillator.stop(now+duration);}
function startMelody(){clearInterval(audioTimer);const notes=[261.63,329.63,392,523.25,440,392,329.63,293.66,261.63,0,329.63,392,293.66,0,261.63,0];audioTimer=setInterval(()=>{const f=notes[melodyIndex++%notes.length];if(f)tone(f,1.1);},650);}
$('sound').addEventListener('click',async()=>{if(state.sound){state.sound=false;clearInterval(audioTimer);await audioContext?.suspend();}else{try{const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)throw Error();audioContext??=new Ctx();await audioContext.resume();state.sound=true;startMelody();tone(392);}catch{say('The music box is taking a nap in this browser.');return;}}state.soundWanted=state.sound;$('sound').textContent='Sound: '+(state.sound?'on':'off');$('sound').setAttribute('aria-pressed',String(state.sound));$('saved-sound').hidden=true;savePreferences();});
function motionUI(){document.body.classList.toggle('still',!state.motion);$('motion').textContent='Motion: '+(state.motion?'on':'off');$('motion').setAttribute('aria-pressed',String(!state.motion));}
$('motion').addEventListener('click',()=>{state.motion=!state.motion;motionUI();savePreferences();});motionUI();
$('wander').addEventListener('click',()=>{welcomeOff();viewport.focus({preventScroll:true});say('Click the meadow. I’ll take the scenic route.');});$('welcome-close').addEventListener('click',()=>{welcomeOff();viewport.focus({preventScroll:true});});
document.querySelectorAll('[data-travel]').forEach(b=>b.addEventListener('click',()=>travel(b.dataset.travel)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openJournal(b.dataset.open)));$('close-journal').addEventListener('click',closeJournal);$('back-to-world').addEventListener('click',closeJournal);journal.addEventListener('cancel',event=>{event.preventDefault();closeJournal();});journal.addEventListener('click',event=>{if(event.target===journal){const r=journal.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeJournal();}});$('interact').addEventListener('click',()=>state.near&&openJournal(state.near));
let bugIndex=0;const bugLines=['I’m not a bug. I’m an undocumented resident.','My rent is one Redis key. It expires tomorrow.','I tried async yoga. Still waiting to be awaited.','Please don’t squash me. I have dependent packages.','Works on my meadow.'];$('bug').addEventListener('click',()=>{welcomeOff();say(bugLines[bugIndex++%bugLines.length],6500);tone(659,.2);});
viewport.addEventListener('pointerdown',event=>{if(event.target.closest('button'))return;welcomeOff();viewport.focus({preventScroll:true});const r=viewport.getBoundingClientRect(),x=(event.clientX-r.left-state.ox)/state.scale,y=(event.clientY-r.top-state.oy)/state.scale;if(!walkable(x,y)){say('A little too much shrubbery. Try the meadow.');return;}state.path=route(x,y);state.pending=null;if(state.path.length)showTarget(x,y);});
const keyDirections={w:'up',ArrowUp:'up',a:'left',ArrowLeft:'left',s:'down',ArrowDown:'down',d:'right',ArrowRight:'right'};
window.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('village-map').hidden&&!journal.open){showMap(false);return;}if(journal.open||event.ctrlKey||event.metaKey||event.altKey)return;if(event.target.closest('button,a,input,textarea,select')&&event.target!==viewport)return;const dir=keyDirections[event.key]||keyDirections[event.key.toLowerCase()];if(dir){event.preventDefault();welcomeOff();state.overview=false;state.keys.add(dir);state.path=[];state.pending=null;$('destination').style.display='none';}if(event.key==='Escape'&&!$('village-map').hidden){showMap(false);return;}if(event.key.toLowerCase()==='e'&&state.near){event.preventDefault();openJournal(state.near);}});
window.addEventListener('keyup',event=>{const dir=keyDirections[event.key]||keyDirections[event.key.toLowerCase()];if(dir)state.keys.delete(dir);});window.addEventListener('blur',()=>state.keys.clear());document.addEventListener('visibilitychange',()=>{state.keys.clear();if(document.hidden){clearInterval(audioTimer);audioContext?.suspend();}else if(state.sound){audioContext?.resume().catch(()=>{});startMelody();}});
document.querySelectorAll('[data-dir]').forEach(b=>{b.addEventListener('pointerdown',event=>{event.preventDefault();welcomeOff();state.path=[];state.pending=null;state.overview=false;state.keys.add(b.dataset.dir);b.setPointerCapture(event.pointerId);});b.addEventListener('click',event=>{if(event.detail!==0)return;const dirs={up:[0,-45],down:[0,45],left:[-45,0],right:[45,0]},[dx,dy]=dirs[b.dataset.dir];if(walkable(state.x+dx,state.y+dy)){state.x+=dx;state.y+=dy;draw();}});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>state.keys.delete(b.dataset.dir));});
function tick(time){const dt=Math.min((time-state.last)/1000||0,.04);state.last=time;let dx=0,dy=0,moving=false;if(!journal.open){dx=Number(state.keys.has('right'))-Number(state.keys.has('left'));dy=Number(state.keys.has('down'))-Number(state.keys.has('up'));const speed=240;if(dx||dy){const norm=Math.hypot(dx,dy);dx=dx/norm*speed*dt;dy=dy/norm*speed*dt;if(walkable(state.x+dx,state.y))state.x+=dx;if(walkable(state.x,state.y+dy))state.y+=dy;moving=true;}else if(state.path.length){const p=state.path[0],distance=Math.hypot(p.x-state.x,p.y-state.y),step=speed*dt;dx=p.x-state.x;if(distance<=step){state.x=p.x;state.y=p.y;state.path.shift();}else{state.x+=(p.x-state.x)/distance*step;state.y+=(p.y-state.y)/distance*step;}moving=true;if(!state.path.length){$('destination').style.display='none';if(state.pending){const id=state.pending;state.pending=null;openJournal(id);}}}}player.classList.toggle('walking',moving&&state.motion);if(Math.abs(dx)>.1)player.classList.toggle('facing-left',dx<0);draw();requestAnimationFrame(tick);}
document.querySelectorAll('[data-depth]').forEach(el=>el.style.zIndex=String(100+Number(el.dataset.depth)));
const art=document.querySelector('.world-art');
function artLoaded(){if(art.naturalWidth>0){$('load-note').hidden=true;}else{$('load-note').textContent='The meadow could not load. Use the recruiter field guide in the header to keep exploring.';}}
art.addEventListener('load',artLoaded);art.addEventListener('error',artLoaded);if(art.complete)artLoaded();
window.addEventListener('village-open',event=>openJournal(event.detail));if(location.hash==='#demo')openJournal('work');
new ResizeObserver(camera).observe(viewport);requestAnimationFrame(tick);setTimeout(()=>$('speech').hidden=true,8000);
})();
