'use strict';
/* Deterministic teaching simulation. No network requests or real benchmarks. */
window.createBackendLab = function () {
 const state={now:0,dbUp:true,cacheUntil:null,requests:0,hits:0,reads:0,jobs:[],nextJob:1,logs:[],path:[],message:'Send a request to start. The database is open for business.'};
 const log=text=>{state.logs.unshift(`t=${(state.now/1000).toFixed(0)}s · ${text}`);state.logs=state.logs.slice(0,40);};
 const cached=()=>state.cacheUntil!==null&&state.now<state.cacheUntil;
 function request(){state.requests++;state.path=['api','cache'];if(cached()){state.hits++;state.message='200 OK · Cache hit. The database gets a tea break. Illustrative lookup: 8 ms.';log('Cache hit; no database read.');return;}state.path.push('database');if(state.dbUp){state.reads++;state.cacheUntil=state.now+5000;state.message='200 OK · Database read; cached for 5 simulated seconds. Illustrative lookup: 120 ms.';log('Cache miss → database → cache populated (TTL 5s).');return;}state.path.push('worker');let job=state.jobs.find(j=>j.status==='queued');if(!job){job={id:state.nextJob++,status:'queued',attempts:0,due:state.now+1000};state.jobs.push(job);log(`Job ${job.id} queued; first retry in 1s.`);}else log(`Lookup coalesced with queued job ${job.id}; no duplicate job.`);state.message=`202 Accepted · The database is having tea. Lookup job ${job.id} is queued; the original request has not succeeded.`;}
 function advance(){state.now+=1000;if(state.cacheUntil!==null&&!cached()){state.cacheUntil=null;log('Cache TTL expired.');}state.path=[];for(const j of state.jobs){if(j.status!=='queued'||j.due>state.now)continue;j.attempts++;state.path=['worker','database'];if(state.dbUp){j.status='done';state.reads++;state.cacheUntil=state.now+5000;state.path.push('cache');state.message=`Job ${j.id} completed on retry ${j.attempts}. A new request can read the cache.`;log(state.message);}else if(j.attempts>=3){j.status='failed';state.message=`Job ${j.id} moved to the dead-letter list after 3 failed retries.`;log(state.message);}else{j.due=state.now+1000*2**j.attempts;state.message=`Job ${j.id} retry ${j.attempts} failed. Next attempt in ${2**j.attempts}s.`;log(state.message);}}}
 function toggle(){state.dbUp=!state.dbUp;log(`Database ${state.dbUp?'restored':'stopped'}. Existing cache remains valid until expiry.`);state.message=state.dbUp?'Database restored. Advance time to run due retries.':'Database stopped. Warm cache still works; clear it to exercise the failure path.';}
 function clear(){state.cacheUntil=null;log('Cache explicitly cleared.');state.message='Cache cleared. The next request must consult the database.';}
 function replay(){let count=0;for(const j of state.jobs){if(j.status==='failed'){j.status='queued';j.attempts=0;j.due=state.now+1000;count++;}}log(`${count} failed job(s) scheduled for replay.`);state.message=count?'Replay scheduled. Advance time to process it.':'No failed jobs to replay.';}
 return {state,cached,request,advance,toggle,clear,replay};
};
window.mountBackendLab=function(root){const panel=root.querySelector('#backend-lab');if(!panel)return;let lab=window.createBackendLab();
 const find=id=>panel.querySelector('#'+id);
 function render(){const s=lab.state;find('lab-status').textContent=s.message;find('lab-clock').textContent=(s.now/1000)+'s';find('lab-counts').textContent=`${s.requests} requests · ${s.hits} cache hits · ${s.reads} database reads`;find('lab-db').textContent=s.dbUp?'Stop database':'Restore database';find('lab-cache-state').textContent=lab.cached()?`Warm · ${Math.ceil((s.cacheUntil-s.now)/1000)}s left`:'Empty';find('lab-db-state').textContent=s.dbUp?'Available':'Unavailable';find('lab-queue-state').textContent=s.jobs.filter(j=>j.status==='queued').length+' queued';panel.querySelectorAll('[data-service]').forEach(el=>el.classList.toggle('active',s.path.includes(el.dataset.service)));find('lab-log').replaceChildren(...s.logs.map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));find('lab-jobs').replaceChildren(...s.jobs.map(j=>{const li=document.createElement('li');li.textContent=`Job ${j.id}: ${j.status} · retries ${j.attempts}/3${j.status==='queued'?' · due at '+j.due/1000+'s':''}`;return li;}));find('lab-empty').hidden=s.jobs.length>0;find('lab-replay').disabled=!s.jobs.some(j=>j.status==='failed');}
 for(const [id,method]of Object.entries({'lab-send':'request','lab-step':'advance','lab-db':'toggle','lab-clear':'clear','lab-replay':'replay'}))find(id).addEventListener('click',()=>{lab[method]();render();});find('lab-reset').addEventListener('click',()=>{lab=window.createBackendLab();render();});render();
};
